- test/harmony-regression/HarmonyRegression.ipynb
Fix to allow the notebooks to run in SIT when run from Bamboo by allowing the case where the harmony_host_url variable is set to the internal load balancer instead of the semi-public URL.
> HARMONY-571: Fix harmony_host_url value in SIT

- test/harmony-regression/HarmonyRegression.ipynb
Needed until https://bugs.earthdata.nasa.gov/browse/HYRAX-387 is fixed
> HARMONY-778: Temporarily comment out cells using variable subsetter

- script/test.sh
Fix now that we can hit the harmony SIT URL from within the SIT account.
> HARMONY-841: Update SIT to use https://harmony.sit.earthdata.nasa.gov

- test/sds/SDS_Regression.ipynb
This PR does two things:
* Activates the HOSS all-variable, no-bounding-box request. This should work now UAT is >= 0.0.389 (currently 0.0.394).
* Removes the download of the HOSS input granule for visual display. When the tests were run for the 0.0.394 UAT release, there was a CloudFront error retrieving the source granule for the HOSS data. I think that's because this granule is hosted by GHRC in their Cumulus instance. The download is non-critical, so I just removed it.
> DAS-1115 - Activate HOSS-all variable, no bounding box request.

- test/sds/SDS_Regression.ipynb
This PR mainly adds regression tests for the new Segmented Trajectory Subsetter service, including:
* A variable subset.
* A temporal subset.
* A bounding box spatial subset.
* A polygon spatial subset.
In addition:
* Some tests have their assertions moved prior to plotting outputs (such as establishing all expected variables are present), so that the failure is on the assertion, not on a bad attempt to plot data.
* I've added green output text to make it clearer that a cell succeeded, particularly in the case where a test doesn't produce a plot.
> DAS-1265 - Add regression tests for SDS Segmented Trajectory Subsetter.

- test/harmony/Harmony.ipynb
I noticed our regression tests were failing. The cause was the change of the name of the ASF GDAL subsetter service to the harmony-gdal-adapter service.
> DAS-1384: Rename of ASF GDAL subsetter to harmony-gdal-adapter.

- test/run_notebooks.sh
When we changed the docker run command to remove the container on exit with the
`--rm` flag, we inadvertently stopped the script from fetching the container
exit code and we were always reporting success.
This change reverts the docker run to keep the container and we remove the
container explicitly after fetching the result.
I adding a cell to the HGA_regression.ipynb that says
`assert true == false, "this test designed to fail"
`
Next I built and ran the hga tests, I saw that the tests reported a success even though they shouldn't.
```
papermill.exceptions.PapermillExecutionError:
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
NameError …
```
> fixes docker run command,  now report actual result of container exit code

- test/hga/HGA_Regression.ipynb
Sentinel 1 has varaibles of different grid sizes and cannot be combined into a
single grid, test that the correct error is raised by the service.
DAS-1479
This can be tested locally by building the code from https://github.com/nasa/harmony-gdal-adapter/pull/16 and updating 
```
harmony_host_url = 'https://localhost:3000'
```
And using a local harmony client
```
collection_data = {
'https://localhost:3000': {
'env': Environment.UAT,
'avnir_collection': Collection(id='C1244141281-EEDTEST'),
'sentinel_collection': Collection(id='C1244141250-EEDTEST'),
'uavsar_collection': Collection(id='C1244141264-EEDTEST'),
'mur_collection': Collection(id='C1238621141-POCLOUD'),
} 
}
environment_information = collection_data.get(harmony_host_url)
if environment_information is not None:
harmony_client = …
```
> Adds regression to test incompatible variables.

- test/hga/HGA_Regression.ipynb
Before adding this we were not raising an exception when the netcdf4 file could
not be converted to GeoTIFF, and when we added that, we need to catch that in the old tests place..
DAS-1479
> Update regression tests to catch new raised exception.

- test/Dockerfile
This PR arose from trawling through logs in Bamboo following test failures. This is an attempt to reduce the output from conda, so that the actual test results are easier to determine from the logs. As I bonus, I've also removed the Pip installation of `conda-lock` because this package was being installed via _both_ Pip and conda, and only needed to be installed by one of the two.
DAS-1495 - I've borrowed the ticket reference for the epic relating to SDS regression test changes for this PR.
* Pull the new branch to your local environment.
* Build one of the Docker images (e.g., `make sds-image`).
* Use `run_notebooks.sh` to run the updated Docker image and ensure it installs everything correctly and the tests run.
> DAS-1495 - Make conda commands less verbose.

- test/sds/SDS_Regression.ipynb
This PR fixes an issue I discovered when running the HOSS regression tests. The temporal test no longer considers the `H1000` variable a valid path without a preceding `/`. This PR adds that slash.
DAS-1590 (discovered while testing)
* Pull this branch locally.
* Start a Jupyter notebook server.
* Run all the cells prior to the Swath Projector tests.
* Run the first cell listed under "Harmony OPeNDAP SubSetter (HOSS)" (it sets up things including `hoss_info`.
* Run the "HOSS temporal subset request" test. It should run and pass.
* ~~Acceptance criteria met~~
> DAS-1590 - Update HOSS temporal regression test variable path.

- test/sds/SDS_Regression.ipynb
This PR fixes a bug introduced with the regression tests for using HOSS/MaskFill with a projection-gridded collection. While the cell that submits the Harmony request is wrapped in logic to only run the test for environments that are configured for testing, the plotting cells were not. When running the tests against the production environment, these latter cells were throwing errors, primarily because they refer to variables defined in code blocks that don't get run in that first cell.
This PR updates these tests to wrap all associated cells in conditional logic to only run the plotting functionality if the environment that the tests are run against has data configured to test with.
DAS-1590
* Pull this branch of the repository.
* Run the notebook twice - first against UAT, then against …
> DAS-1590 - Ensure all tests are wrapped in logic to only run for expected environments.

- README.md
- script/clean-up-docker-images.sh
- script/test-in-bamboo.sh
- test/Makefile
- test/run_notebooks.sh
Adds script/test-in-bamboo.sh in order to simplify regression testing.  This
script downloads the regression test images from github's container registry
and then runs the run_notebooks.sh testing script.
Additionally it renames the default images from `harmony/regression-test-<img>` to `ghrc.io/nasa/regression-test-<img>`
DAS-1761
If you set these environmental variables:
``` text
HARMONY_ENVIRONMENT
HARMONY_HOST_URL
AWS_SECRET_ACCESS_KEY
AWS_ACCESS_KEY_ID
EDL_USER
EDL_PASSWORD
```
From your project root directory, you should be able to run:
``` bash
./scripts/test-in-bamboo.sh
```
And see it download the default images and run the regression tests.
After it finishes, you can run 
``` bash
./script/clean-up-docker-images.sh
```
And watch it clean up all of the pulled docker images from …
> Add test-in-bamboo.sh option

- .gitignore
- script/test-in-bamboo.sh
This PR ensures that the current Bamboo behaviour of pushing output notebooks to a bucket in the relevant Harmony S3 bucket is maintained.
DAS-1747.
* Run this script with appropriate environment variables set for authentication against the correct Harmony environment. Upon completion the output notebooks should be correctly pushed to S3.
> DAS-1747 - Push notebook outputs to S3.

- script/test-in-bamboo.sh
The previous PR I made did exactly the opposite of what it should... it the test-in-bamboo.sh script will currently only try to push to S3 when `REGRESSION_TEST_OUTPUT_BUCKET` has zero length. This PR fixes that.
Otherwise, things are behaving as expected in Bamboo. :tada:
DAS-1747
Use the if-else logic from the bottom of the script to check it behave as expected when the environment variable for the S3 bucket is, or is not set.
> DAS-1747 - Ensure aws s3 cp called when REGRESSION_TEST_OUTPUT_BUCKET is set.

- script/test-in-bamboo.sh
What the title says:
Before,  'latest' was the the default tag/value for an image that did not have corresponding bamboo environment variable.
Now, it reads the tag from the `version.txt` associated with the image.
[DAS-1970](https://bugs.earthdata.nasa.gov/browse/DAS-1970)
I don't think this can be tested locally.  But if you checkout this branch and run the changed script from the root directory.
``` sh
HARMONY_ENV=sit ./script-test-in-bamboo.sh
```
You should see the file pull all regression images with their respective tags:
Pulling image: ghcr.io/nasa/regression-tests-harmony:0.1.3
~Additionally, when this is merged, all of the image values in SIT Bamboo should be deleted. The image names, can remain, but their values should be empty. This should let the actual image tag show up in …
> DAS-1970: Switches image tag to be read from version.txt

- script/image_name.sh
- script/test-in-bamboo.sh
- test/run_notebooks.sh
Read from version.txt in both run_notebooks.sh and test-in-bamboo.sh
Uses SCRIPT_DIR to correctly locate version.txt
Parses the bash input parameters for `run_notebooks.sh`
When `run_notebooks.sh` is run with no params or with a list of tests to
run. e.g. `hga n2z` it will run with the latest image that must be built
locally (no change from how this worked before).  The change is that
`run_notebooks.sh` now takes a flag `--use-versions` which will control whether
`latest` or the value from `version.txt` is used as the docker image tag.
This flag is set in the `test-in-bamboo.sh` file so that CI will always run with the tagged version from version.txt (if it's not overridden by bamboo environment variables.)
[DAS-1970](https://bugs.earthdata.nasa.gov/browse/DAS-1970)
You can checkout this …
> DAS-1970: bugfix

- test/run_notebooks.sh
-------
added a docker rm to the ctrl_c function
DAS-1972 is not directly related, but what I was working on when I found this.
check out main.
Run a notebook and kill it before it completes.
> ./run_notebooks.sh hag
Interrupt with ctrl-c.
Examine the containers in your docker desktop.  You should see some exited containers.
Next check out this branch, and follow the same steps, you should no longer see exited containers.
* [ n/a ] Acceptance criteria met
* [ n/a ] Tests added/updated (if needed) and passing
* [ n/a ] Documentation updated (if needed)
> DAS-1972: Attempts to clean up containers on kill signal.

- .github/workflows/notebook-test-suite.yml
Fixes the ability to provide a regression image tag when running the a notebook test by hand
I was trying to test hybig in production and I wanted to specify the version of the regression to run, realized that it wasn't being picked up by github actions.
None
You can fork and check your own repository, or you can look at this output. Check the command under pull docker image
https://github.com/flamingbear/harmony-regression-tests/actions/runs/11392069321/job/31697286308
```
Run docker pull ghcr.io/nasa/regression-tests-hybig:0.0.8
```
* [N/A] Acceptance criteria met
* [N/A] Tests added/updated (if needed) and passing
* [N/A] Documentation updated (if needed)
* [N/A] CHANGELOG updated with the changes for this PR
> Pass input docker-image-tag to docker pull

- .github/workflows/notebook-test-suite.yml
Add harmony environment name to the harmony-regression-tests action name and notification. Below is the difference of the Action Name change between main and the PR branch.
Email notification has similar changes.
HARMONY-1933
Run Jupyter notebook based test suite manually to see the Action name and email notification changes, and they are more informative with the Harmony environment in them.
> HARMONY-1933: Add harmony environment name to the harmony-regression-tests action name and notification.

- README.md
This PR adds a few lines to the README.md on how to configure Git LFS (Large File System). This is currently used for the reference files in the NSIDC ICESat-2 Trajectory Subsetter test notebook, but will (and should) likely be incorporated into other notebooks.
Follow the new instructions in the README.md to configure Git LFS.
Execute the [NSIDC-ICESAT2_Regression.ipynb](https://github.com/nasa/harmony-regression-tests/blob/main/test/nsidc-icesat2/NSIDC-ICESAT2_Regression.ipynb) notebook. All tests should pass. 
Note 1: And indicator that Git LFS is correctly configured will be when the /nsidc-icesat2/reference_files have these sizes:
Note 2: If you haven't worked in this repository recently, you may have to re-create the nsidc-icesat2 conda environment used in the notebook.
> Add install and configuration commands for git-lfs to README.md

- CHANGELOG.md
- config/services_tests_config_prod.json
- config/services_tests_config_uat.json
opera-rtc-s1-browse depends on HyBIG, so we should run the tests when HyBIG is deployed.
[DAS-2276 sort of](https://bugs.earthdata.nasa.gov/browse/DAS-2276)
Trust?  wait until HyBIG is deployed again and see that opera tests are included? 
* [n/a] Acceptance criteria met
* [n/a] Tests added/updated (if needed) and passing
* [n/a] Documentation updated (if needed)
> DAS-2276: opera-rtc-s1-browse tests run with hybig deployments

- .github/CODEOWNERS
This PR adds a `CODEOWNERS` file. These will be default reviewers, with at least one approval from the listed reviewers needed to merge in to `main`.
N/A (TRT-680 is related, as making sure we don't add `git lfs` artefacts back to the repo was the motivation here)
Check this file looks right, per the [documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners).
* ~~Acceptance criteria met~~
* ~~CHANGELOG updated with the changes for this PR~~
* ~~Service's `version.txt` file changed if appropriate~~
> TRT-680: Add CODEOWNERS file.

- test/hga/HGA_Regression.ipynb
This PR adds a warning to the HGA test suite. It doesn't need to be released.
I was going to convert the tests over to use `earthdata-hashdiff`, but that package requires Python 3.11 or higher, whilst the current version of GDAL used by the tests needs 3.10 or lower. Changing the version of GDAL breaks some of the tests (they no longer work with some of the output projections).
For a service that is basically unused in production, and will either be decommissioned or drastically descoped in the future, the warning added should be sufficient for now.
N/A
N/A
* ~~Acceptance criteria met~~
* ~~CHANGELOG updated with the changes for this PR~~
* ~~Service's `version.txt` file changed if appropriate~~
* …
> TRT-680: Add warning to HGA test suite.
